spawnpoints:
  '1':
    world: world_1
    x: 0.5760213691924665
    y: 64.5
    z: -101.3477350965392
    yaw: -3.1891465E-4
    pitch: -0.15080263
  '2':
    world: world_1
    x: 21.492904593633593
    y: 64.5
    z: -82.50515196290151
    yaw: 26.699615
    pitch: -0.4508235
  '3':
    world: world_1
    x: 40.458651682764035
    y: 64.5
    z: -62.37204260303039
    yaw: 34.4997
    pitch: -1.8005817
  '4':
    world: world_1
    x: 40.489373905356025
    y: 64.5
    z: -31.49626814004815
    yaw: 53.399487
    pitch: -1.3505856
  '5':
    world: world_1
    x: 40.435361017031454
    y: 64.5
    z: 0.4771537148084135
    yaw: 90.29927
    pitch: -3.1505382
  '6':
    world: world_1
    x: 40.28394213633874
    y: 64.5
    z: 32.530395154773146
    yaw: 128.24971
    pitch: -2.1004608
  '7':
    world: world_1
    x: 40.44272964827383
    y: 64.5
    z: 64.49883595091347
    yaw: 149.2498
    pitch: -2.7004488
  '8':
    world: world_1
    x: 21.4989696869348
    y: 64.5
    z: 83.58476401517918
    yaw: 164.99937
    pitch: -1.3503784
  '9':
    world: world_1
    x: 0.4535784778498867
    y: 64.5
    z: 102.24932371773272
    yaw: -179.85078
    pitch: -0.6001619
  '10':
    world: world_1
    x: -20.456705751589467
    y: 64.5
    z: 83.35451892745913
    yaw: -163.80199
    pitch: -1.0502058
  '11':
    world: world_1
    x: -39.44808555625054
    y: 64.5
    z: 64.38368484645436
    yaw: -145.05212
    pitch: -1.6500685
  '12':
    world: world_1
    x: -39.377682498732966
    y: 64.5
    z: 32.36577227689091
    yaw: -127.803024
    pitch: -2.5498726
  '13':
    world: world_1
    x: -39.4264866608621
    y: 64.5
    z: 0.4517573790207828
    yaw: -89.7052
    pitch: -3.1496444
  '14':
    world: world_1
    x: -39.33127520843722
    y: 64.5
    z: -31.441884773170663
    yaw: -51.756714
    pitch: -1.0495754
  '15':
    world: world_1
    x: -39.52183055642045
    y: 64.5
    z: -63.56613224557435
    yaw: -32.859436
    pitch: -2.0993454
  '16':
    world: world_1
    x: -20.49522003071147
    y: 64.5
    z: -82.4924574626331
    yaw: -14.111725
    pitch: -1.9493214
messages:
  prefix:  &r
  error-console: '&fNo puedes usar este comando en la consola crack'
  error-permission: '&fNo tienes permiso para ejecutar este comando'
  chest-reset: '&fCofres Reiniciados'
  setspawn-syntax: '&fUsalo asi: /setspawn <spawnpoint>'
  setspawn-notvalid: '&fNumero no valido.'
  setspawn-number: '&fDebe de ser un numero entre 1 y 16'
  setspawn-set: '&fSpawnpoint &7%s &fcolocado'
  server-full: '&fEl servidor esta lleno'
  cancel-move: '&fAún no te puedes mover.'
  chest-refill: '&f¡Los cofres han sido rellenados!'
  drop-opening: '&fUn jugador está abriendo el drop en &7X: %d, Z: %d'
  drop-opening-wait: '&fEl drop se esta abriendo, tienes que esperar &7%d &fsegundos.'
  border-300: '&fEl borde se esta cerrando &7| &f300 x 300'
  border-150: '&fEl borde se esta cerrando &7| &f150 x 150'
  border-50: '&fEl borde se esta cerrando &7| &f50 x 50'
  player-join: '&7%s&f &r&fse ha unido al juego &7%d/16'
  admin-join: '&7%s&7 &r&fse ha unido al juego'
  player-quit: '&7%s&f &r&fha abandonado el juego &7 %d/16'
  admin-quit: '&7%s&f &r&fha abandonado el juego'
  player-death: '&7%s &fHa sido eliminado por &7%s. &7Aun restan %d jugadores'
  border-30sec: '&fEl borde se cerrará en &730 segundos'
  victory: '&fEl ganador es &d&l%s&e&l!'
  start10: '&fLa partida empieza en &7%d'
  start60: '&fLa partida empieza en &71 &fminuto'
  start90: '&fLa partida empieza en &71 &fminuto y &730 &fsegundos'
  grace-period-start: '&fEl tiempo de gracia ha comenzado. Los jugadores no pueden
    recibir daño por &730 segundos'
  grace-period-end: '&fEl tiempo de gracia ha terminado. ¡Ya puedes recibir daño!'
  drop-message: '&dUn drop está cayendo en §fX: %d Z: %d'
  game-started: '&dEl juego ya ha empezado. &fIntentalo mas tarde'
  player-rejoin: '&fBienvenido de vuelta'
lootItemst2:
  '0':
    material: GOLDEN_HELMET
    name: §f§l- Armadura §f§l§nNivel 2§f - §f
    lore:
      - §f • Armadura ||
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '1':
    material: GOLDEN_CHESTPLATE
    name: §f§l- Armadura §f§l§nNivel 2§f - §f
    lore:
      - §f • Armadura ||
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '2':
    material: GOLDEN_LEGGINGS
    name: §f§l- Armadura §f§l§nNivel 2§f - §f
    lore:
      - §f • Armadura ||
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '3':
    material: GOLDEN_BOOTS
    name: §f§l- Armadura §f§l§nNivel 2§f - §f
    lore:
      - §f • Armadura ||
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '4':
    material: CHAINMAIL_HELMET
    name: §f§l- Armadura §f§l§nNivel 3§f - §f
    lore:
      - §f • Armadura |||
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '5':
    material: CHAINMAIL_CHESTPLATE
    name: §f§l- Armadura §f§l§nNivel 3§f - §f
    lore:
      - §f • Armadura |||
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '6':
    material: CHAINMAIL_LEGGINGS
    name: §f§l- Armadura §f§l§nNivel 3§f - §f
    lore:
      - §f • Armadura |||
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '7':
    material: CHAINMAIL_BOOTS
    name: §f§l- Armadura §f§l§nNivel 3§f - §f
    lore:
      - §f • Armadura |||
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '8':
    material: SHIELD
    name: §f§l- Escudo§f - §f
    lore:
      - §f • ¡Protegete de la jalea!
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '9':
    material: IRON_CHESTPLATE
    name: §f§l- Armadura §f§l§nNivel 4§f - §f
    lore:
      - §f • Armadura ||||
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '10':
    material: IRON_HELMET
    name: §f§l- Armadura §f§l§nNivel 4§f - §f
    lore:
      - §f • Armadura ||||
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '11':
    material: GOLDEN_CARROT
    name: §f§l- Zanahoria§f - §f
    lore:
      - §f • Recuerda alimentarte sanamente
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '12':
    material: GOLDEN_APPLE
    name: §f§l- Sponch PiñaCool§f - §f
    customModelData: 2
    lore:
      - §f • ¡Diversión por niveles!
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '13':
    material: GOLDEN_APPLE
    name: §f§l- Sponch§f - §f
    customModelData: 1
    lore:
      - §f • ¡Diversión por niveles!
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '14':
    material: BROWN_DYE
    name: §f§l- Localizador§f - §f
    customModelData: 12
    lore:
      - §f • Te muestra la posición de otros jugadores
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '15':
    material: BROWN_DYE
    name: §f§l- Botiquin§f - §f
    customModelData: 13
    lore:
      - §f • Restaura 6 puntos de vida
      - §f • Tarda 5 segundos en activarse
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '16':
    material: CROSSBOW
    name: §f§l- Inigualable§f - §f
    customModelData: 5
    lore:
      - §f • Munición ||||||||||||||||||||||||||||||||||||||||||||||||||
      - §f • Daño 0.025
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '17':
    material: CROSSBOW
    name: §f§l- Irresistible§f - §f
    customModelData: 4
    lore:
      - §f • Munición ||||||||||||||||||||||||||||||||
      - §f • Daño 0.35
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '18':
    material: CROSSBOW
    name: §f§l- Sabrosa§f - §f
    customModelData: 7
    lore:
      - §f • Munición |||||||||||||||||||||||||
      - §f • Daño 0.41
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '19':
    material: BROWN_DYE
    name: §f§l- Ticket Recompensa§f - §f
    customModelData: 14
    lore:
      - §f • Canjealo con click izquierdo
    minAmount: 1
    maxAmount: 1
    chance: 0.1
drop-zones:
  spawn1:
    corner1:
      - -28.431765313052733
      - -44.505593185941265
    corner2:
      - 28.356711437772272
      - -70.67621876406285
  spawn2:
    corner1:
      - -27.519977996537513
      - -16.46468566164804
    corner2:
      - 28.435502142897395
      - -38.426456934046755
  full:
    corner1:
      - 197.42527443990528
      - 187.6181492037206
    corner2:
      - -197.84408936105598
      - -203.69999998807907
lootItems:
  '0':
    material: LEATHER_HELMET
    name: §f§l- Armadura §f§l§nNivel 1§f - §f
    customModelData: 8
    lore:
      - §f • Armadura |
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '1':
    material: LEATHER_CHESTPLATE
    name: §f§l- Armadura §f§l§nNivel 1§f - §f
    customModelData: 5
    lore:
      - §f • Armadura |
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '2':
    material: LEATHER_LEGGINGS
    name: §f§l- Armadura §f§l§nNivel 1§f - §f
    customModelData: 4
    lore:
      - §f • Armadura |
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '3':
    material: LEATHER_BOOTS
    name: §f§l- Armadura §f§l§nNivel 1§f - §f
    customModelData: 2
    lore:
      - §f • Armadura |
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '4':
    material: SHIELD
    name: §f§l- Escudo§f - §f
    customModelData: 3
    lore:
      - §f • ¡Protegete de la jalea!
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '5':
    material: GOLDEN_APPLE
    name: §f§l- Sponch PiñaCool§f - §f
    customModelData: 2
    lore:
      - §f • ¡Diversión por niveles!
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '6':
    material: GOLDEN_APPLE
    name: §f§l- Sponch§f - §f
    customModelData: 1
    lore:
      - §f • ¡Diversión por niveles!
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '7':
    material: BROWN_DYE
    name: §f§l- Botiquin§f - §f
    customModelData: 13
    lore:
      - §f • Restaura 6 puntos de vida
      - §f • Tarda 5 segundos en activarse
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '8':
    material: GOLDEN_CARROT
    name: §f§l- Zanahoria§f - §f
    customModelData: 7
    lore:
      - §f • Recuerda alimentarte sanamente
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '9':
    material: CROSSBOW
    name: §f§l- Fresa§f - §f
    customModelData: 1
    lore:
      - §f • Munición ||||||||||
      - §f • Daño 1.0
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '10':
    material: CROSSBOW
    name: §f§l- Sponch§f - §f
    customModelData: 2
    lore:
      - §f • Munición ||||||||||
      - §f • Daño 1.0
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '11':
    material: CROSSBOW
    name: §f§l- PiñaCool§f - §f
    customModelData: 3
    lore:
      - §f • Munición ||||||||||
      - §f • Daño 1.0
    minAmount: 1
    maxAmount: 1
    chance: 0.1
dropLoot:
  '0':
    material: IRON_LEGGINGS
    name: §f§l- Armadura §f§l§nNivel 4§f - §f
    lore:
      - §f • Armadura ||||
    minAmount: 1
    maxAmount: 1
    chance: 0.3
  '1':
    material: IRON_BOOTS
    name: §f§l- Armadura §f§l§nNivel 4§f - §f
    lore:
      - §f • Armadura ||||
    minAmount: 1
    maxAmount: 1
    chance: 0.3
  '2':
    material: DIAMOND_HELMET
    name: §f§l- Armadura §f§l§nNivel 5§f - §f
    lore:
      - §f • Armadura |||||
    minAmount: 1
    maxAmount: 1
    chance: 0.3
  '3':
    material: DIAMOND_CHESTPLATE
    name: §f§l- Armadura §f§l§nNivel 5§f - §f
    lore:
      - §f • Armadura |||||
    minAmount: 1
    maxAmount: 1
    chance: 0.3
  '4':
    material: DIAMOND_LEGGINGS
    name: §f§l- Armadura §f§l§nNivel 5§f - §f
    lore:
      - §f • Armadura |||||
    minAmount: 1
    maxAmount: 1
    chance: 0.3
  '5':
    material: DIAMOND_BOOTS
    name: §f§l- Armadura §f§l§nNivel 5§f - §f
    lore:
      - §f • Armadura |||||
    minAmount: 1
    maxAmount: 1
    chance: 0.3
  '6':
    material: BROWN_DYE
    name: §f§l- Ticket Recompensa§f - §f
    customModelData: 14
    lore:
      - §f • Canjealo con click izquierdo
    minAmount: 1
    maxAmount: 1
    chance: 1.0
  '7':
    material: GOLDEN_APPLE
    name: §f§l- Sponch PiñaCool§f - §f
    customModelData: 2
    lore:
      - §f • ¡Diversión por niveles!
    minAmount: 1
    maxAmount: 1
    chance: 0.3
  '8':
    material: GOLDEN_APPLE
    name: §f§l- Sponch§f - §f
    customModelData: 1
    lore:
      - §f • ¡Diversión por niveles!
    minAmount: 1
    maxAmount: 1
    chance: 0.3
  '9':
    material: BROWN_DYE
    name: §f§l- Localizador§f - §f
    customModelData: 12
    lore:
      - §f • Te muestra la posición de otros jugadores
    minAmount: 1
    maxAmount: 1
    chance: 0.3
  '10':
    material: SHIELD
    name: §f§l- Escudo§f - §f
    lore:
      - §f • ¡Protegete de la jalea!
    minAmount: 1
    maxAmount: 1
    chance: 0.3
  '11':
    material: BROWN_DYE
    name: §f§l- Botiquin§f - §f
    customModelData: 13
    lore:
      - §f • Restaura 6 puntos de vida
      - §f • Tarda 5 segundos en activarse
    minAmount: 1
    maxAmount: 1
    chance: 0.3
  '12':
    material: CROSSBOW
    name: §f§l- Culposa§f - §f
    customModelData: 6
    lore:
      - §f • Munición |
      - §f • Daño 200
    minAmount: 1
    maxAmount: 1
    chance: 0.3
  '13':
    material: IRON_HELMET
    name: §f§l- Armadura §f§l§nNivel 4§f - §f
    lore:
      - §f • Armadura ||||
    minAmount: 1
    maxAmount: 1
    chance: 0.3
  '14':
    material: IRON_CHESTPLATE
    name: §f§l- Armadura §f§l§nNivel 4§f - §f
    lore:
      - §f • Armadura ||||
    minAmount: 1
    maxAmount: 1
    chance: 0.3
