spawnpoints:
  '1':
    world: world_1
    x: 0.5760213691924665
    y: 64.5
    z: -101.3477350965392
    yaw: -3.1891465E-4
    pitch: -0.15080263
  '2':
    world: world_1
    x: 21.492904593633593
    y: 64.5
    z: -82.50515196290151
    yaw: 26.699615
    pitch: -0.4508235
  '3':
    world: world_1
    x: 40.458651682764035
    y: 64.5
    z: -62.37204260303039
    yaw: 34.4997
    pitch: -1.8005817
  '4':
    world: world_1
    x: 40.489373905356025
    y: 64.5
    z: -31.49626814004815
    yaw: 53.399487
    pitch: -1.3505856
  '5':
    world: world_1
    x: 40.435361017031454
    y: 64.5
    z: 0.4771537148084135
    yaw: 90.29927
    pitch: -3.1505382
  '6':
    world: world_1
    x: 40.28394213633874
    y: 64.5
    z: 32.530395154773146
    yaw: 128.24971
    pitch: -2.1004608
  '7':
    world: world_1
    x: 40.44272964827383
    y: 64.5
    z: 64.49883595091347
    yaw: 149.2498
    pitch: -2.7004488
  '8':
    world: world_1
    x: 21.4989696869348
    y: 64.5
    z: 83.58476401517918
    yaw: 164.99937
    pitch: -1.3503784
  '9':
    world: world_1
    x: 0.4535784778498867
    y: 64.5
    z: 102.24932371773272
    yaw: -179.85078
    pitch: -0.6001619
  '10':
    world: world_1
    x: -20.456705751589467
    y: 64.5
    z: 83.35451892745913
    yaw: -163.80199
    pitch: -1.0502058
  '11':
    world: world_1
    x: -39.44808555625054
    y: 64.5
    z: 64.38368484645436
    yaw: -145.05212
    pitch: -1.6500685
  '12':
    world: world_1
    x: -39.377682498732966
    y: 64.5
    z: 32.36577227689091
    yaw: -127.803024
    pitch: -2.5498726
  '13':
    world: world_1
    x: -39.4264866608621
    y: 64.5
    z: 0.4517573790207828
    yaw: -89.7052
    pitch: -3.1496444
  '14':
    world: world_1
    x: -39.33127520843722
    y: 64.5
    z: -31.441884773170663
    yaw: -51.756714
    pitch: -1.0495754
  '15':
    world: world_1
    x: -39.52183055642045
    y: 64.5
    z: -63.56613224557435
    yaw: -32.859436
    pitch: -2.0993454
  '16':
    world: world_1
    x: -20.49522003071147
    y: 64.5
    z: -82.4924574626331
    yaw: -14.111725
    pitch: -1.9493214
messages:
  prefix:  &r
  error-console: '&fNo puedes usar este comando en la consola crack'
  error-permission: '&fNo tienes permiso para ejecutar este comando'
  chest-reset: '&fCofres Reiniciados'
  setspawn-syntax: '&fUsalo asi: /setspawn <spawnpoint>'
  setspawn-notvalid: '&fNumero no valido.'
  setspawn-number: '&fDebe de ser un numero entre 1 y 16'
  setspawn-set: '&fSpawnpoint &7%s &fcolocado'
  server-full: '&fEl servidor esta lleno'
  cancel-move: '&fAún no te puedes mover.'
  chest-refill: '&f¡Los cofres han sido rellenados!'
  drop-opening: '&fUn jugador está abriendo el drop en &7X: %d, Z: %d'
  drop-opening-wait: '&fEl drop se esta abriendo, tienes que esperar &7%d &fsegundos.'
  border-300: '&fEl borde se esta cerrando &7| &f300 x 300'
  border-150: '&fEl borde se esta cerrando &7| &f150 x 150'
  border-50: '&fEl borde se esta cerrando &7| &f50 x 50'
  player-join: '&7%s&f &r&fse ha unido al juego &7%d/16'
  admin-join: '&7%s&7 &r&fse ha unido al juego'
  player-quit: '&7%s&f &r&fha abandonado el juego &7 %d/16'
  admin-quit: '&7%s&f &r&fha abandonado el juego'
  player-death: '&7%s &fHa sido eliminado. &7Aun restan %d jugadores'
  border-30sec: '&fEl borde se cerrará en &730 segundos'
  victory: '&fEl ganador es &d&l%s&e&l!'
  start10: '&fLa partida empieza en &7%d'
  start60: '&fLa partida empieza en &71 &fminuto'
  start90: '&fLa partida empieza en &71 &fminuto y &730 &fsegundos'
  grace-period-start: '&fEl tiempo de gracia ha comenzado. Los jugadores no pueden recibir daño por &730 segundos'
  grace-period-end: '&fEl tiempo de gracia ha terminado. ¡Ya puedes recibir daño!'
  drop-message: '&dUn drop está cayendo en §fX: %d Z: %d'
lootItems:
  '0':
    material: CROSSBOW
    name: §f§l M401
    customModelData: 8
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '1':
    material: CROSSBOW
    name: §f§l M249
    customModelData: 5
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '2':
    material: BROWN_DYE
    name: §f§l Kar98k
    customModelData: 4
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '3':
    material: GOLDEN_APPLE
    name: §f§l M249
    customModelData: 2
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '4':
    material: BROWN_DYE
    name: §f§l M401
    customModelData: 3
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '5':
    material: BROWN_DYE
    customModelData: 5
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '6':
    material: GOLDEN_APPLE
    customModelData: 1
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '7':
    material: FLINT_AND_STEEL
    customModelData: 7
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '8':
    material: CROSSBOW
    name: §f§l AK47
    customModelData: 7
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '9':
    material: CROSSBOW
    name: §f§l SCAR
    customModelData: 4
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '10':
    material: CROSSBOW
    name: §f§l Kar98k
    customModelData: 6
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '11':
    material: LEATHER_HELMET
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '12':
    material: LEATHER_CHESTPLATE
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '13':
    material: LEATHER_LEGGINGS
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '14':
    material: LEATHER_BOOTS
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '15':
    material: WOODEN_AXE
    minAmount: 1
    maxAmount: 1
    chance: 0.15
  '16':
    material: STONE_AXE
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '17':
    material: WOODEN_SWORD
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '18':
    material: STONE_SWORD
    minAmount: 1
    maxAmount: 1
    chance: 0.05
  '19':
    material: BOW
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '20':
    material: FISHING_ROD
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '21':
    material: ARROW
    minAmount: 5
    maxAmount: 5
    chance: 0.1
  '22':
    material: IRON_INGOT
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '23':
    material: GOLD_INGOT
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '24':
    material: STICK
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '25':
    material: FEATHER
    minAmount: 5
    maxAmount: 5
    chance: 0.1
  '26':
    material: FLINT
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '27':
    material: SALMON
    minAmount: 1
    maxAmount: 1
    chance: 0.08
  '28':
    material: BEEF
    minAmount: 1
    maxAmount: 2
    chance: 0.08
  '29':
    material: PORKCHOP
    minAmount: 1
    maxAmount: 2
    chance: 0.08
  '30':
    material: CHICKEN
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '31':
    material: COOKED_BEEF
    minAmount: 1
    maxAmount: 2
    chance: 0.08
  '32':
    material: COOKED_CHICKEN
    minAmount: 1
    maxAmount: 3
    chance: 0.08
  '33':
    material: COOKED_SALMON
    minAmount: 1
    maxAmount: 3
    chance: 0.08
  '34':
    material: COOKED_PORKCHOP
    minAmount: 1
    maxAmount: 2
    chance: 0.08
  '35':
    material: APPLE
    minAmount: 2
    maxAmount: 2
    chance: 0.08
  '36':
    material: CARROT
    minAmount: 5
    maxAmount: 5
    chance: 0.08
  '37':
    material: MELON_SLICE
    minAmount: 5
    maxAmount: 5
    chance: 0.08
  '38':
    material: BREAD
    minAmount: 1
    maxAmount: 3
    chance: 0.08
  '39':
    material: COOKIE
    minAmount: 5
    maxAmount: 5
    chance: 0.08
  '40':
    material: PUMPKIN_PIE
    minAmount: 1
    maxAmount: 1
    chance: 0.8
dropLoot:
  '0':
    material: STONE_SWORD
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '1':
    material: BOW
    minAmount: 1
    maxAmount: 1
    chance: 0.12
  '2':
    material: FISHING_ROD
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '3':
    material: ARROW
    minAmount: 5
    maxAmount: 5
    chance: 0.1
  '4':
    material: IRON_INGOT
    minAmount: 1
    maxAmount: 1
    chance: 0.13
  '5':
    material: STICK
    minAmount: 1
    maxAmount: 1
    chance: 0.05
  '6':
    material: COOKED_BEEF
    minAmount: 1
    maxAmount: 5
    chance: 0.05
  '7':
    material: APPLE
    minAmount: 2
    maxAmount: 2
    chance: 0.05
  '8':
    material: CARROT
    minAmount: 2
    maxAmount: 2
    chance: 0.05
  '9':
    material: GOLDEN_HELMET
    minAmount: 1
    maxAmount: 1
    chance: 0.12
  '10':
    material: GOLDEN_CHESTPLATE
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '11':
    material: GOLDEN_LEGGINGS
    minAmount: 1
    maxAmount: 1
    chance: 0.11
  '12':
    material: GOLDEN_BOOTS
    minAmount: 1
    maxAmount: 1
    chance: 0.1
  '13':
    material: CHAINMAIL_HELMET
    minAmount: 1
    maxAmount: 1
    chance: 0.09
  '14':
    material: CHAINMAIL_CHESTPLATE
    minAmount: 1
    maxAmount: 1
    chance: 0.08
  '15':
    material: CHAINMAIL_LEGGINGS
    minAmount: 1
    maxAmount: 1
    chance: 0.09
  '16':
    material: CHAINMAIL_BOOTS
    minAmount: 1
    maxAmount: 1
    chance: 0.09
  '17':
    material: IRON_HELMET
    minAmount: 1
    maxAmount: 1
    chance: 0.07
  '18':
    material: IRON_CHESTPLATE
    minAmount: 1
    maxAmount: 1
    chance: 0.05
  '19':
    material: IRON_LEGGINGS
    minAmount: 1
    maxAmount: 1
    chance: 0.06
  '20':
    material: IRON_BOOTS
    minAmount: 1
    maxAmount: 1
    chance: 0.07
  '21':
    material: FLINT_AND_STEEL
    minAmount: 1
    maxAmount: 1
    chance: 0.13
  '22':
    material: DIAMOND
    minAmount: 1
    maxAmount: 1
    chance: 0.04
  '23':
    material: GOLDEN_CARROT
    minAmount: 1
    maxAmount: 1
    chance: 0.07
  '24':
    material: ENCHANTED_GOLDEN_APPLE
    minAmount: 1
    maxAmount: 1
    chance: 0.07