name: HungerGamesHexa
version: '${project.version}'
main: org.hexa.hungergameshexa.HungerGamesHexa
api-version: '1.20'
author: ImRadiGamer
commands:
  start:
    usage: /<command>
    description: Cambia el gamestate
  setspawn:
    usage: /<command>
    description: Coloca las ubicaciones
  lootconfig:
    usage: /<command>
    description: Configura los cofres
  reset:
    usage: /<command>
    description: Reinicia los cofres
  droploot:
    usage: /<command>
    description: Configura el loot de los drops
  drop:
    usage: /<command>
    description: Tira un Drop cuando se desee (Eliminar)
  ganador:
    usage: /<command>
    description: Cambia el gamestate a GANADOR
  esperando:
    usage: /<command>
    description: Cambia el gamestate a ESPERANDO
  setdropzone:
    usage: /<command> <zoneName> corner1|corner2
    description: Coloca esquinas para los drops
  droplocation:
    usage: /<command>
    description: Tira un drop en tu ubicacion
  loott2config:
    usage: /<command>
    description: Configura el loot Tier 2
  instastart:
    usage: /<command>
    description: Comienza la partida automaticamente
  modotorneo:
    usage: /<command>
    description: Activa o desactiva el modo torneo
  getteamsize:
    usage: /<command>
    description: Arroja el tamaño de jugadores
  autostart:
    usage: /<command>
    description: Desactiva el autostart para hacerlo manual
