name: HungerGamesHexa
version: '${project.version}'
main: org.hexa.hungergameshexa.HungerGamesHexa
api-version: '1.20'
commands:
  start:
    usage: /<command>
    description: Cambia el gamestate
  setspawn:
    usage: /<command>
    description: Coloca las ubicaciones
  lootconfig:
    usage: /<command>
    description: Configura los cofres
  reset:
    usage: /<command>
    description: Reinicia los cofres