name: HungerGamesHexa
version: '${project.version}'
main: org.hexa.hungergameshexa.HungerGamesHexa
api-version: '1.20'
commands:
  start:
    usage: /<command>
    description: Cambia el gamestate
  openinv:
    usage: /<command>
    description: Abre el sistema de cofres
