name: HungerGamesHexa
version: '1.0-SNAPSHOT'
main: org.hexa.hungergameshexa.HungerGamesHexa
api-version: '1.20'
commands:
  start:
    usage: /<command>
    description: Cambia el gamestate
  setspawn:
    usage: /<command>
    description: Coloca las ubicaciones
  lootconfig:
    usage: /<command>
    description: Configura los cofres
